version : "3" 
services :
    webserver :
        build :
            context : ./docker/php
            dockerfile : Dockerfile 
        container_name : php_ci_rabbitmq
        ports : 
            - 9484:80
        networks :
            backend-net :
                ipv4_address : 9.21.21.19
        links :
            - memcached
            - mongodb
            - database
        depends_on :
            - memcached
            - mongodb
            - database
        volumes :
            - .:/var/www/html
        command : sh /var/www/html/docker/php/init.sh
    database :
        container_name : db_ci_rabbitmq
        image : mariadb
        ports :
            - "9404:3306"
        networks :
            backend-net :
                ipv4_address : 9.21.21.20
        environment :
            - MYSQL_ROOT_PASSWORD=7*DBci369
            - MYSQL_DATABASE=db_ci
    memcached :
        container_name : memcached_ci_rabbitmq
        image : memcached:alpine
        ports :
            - "9411:11211"
        networks :
            backend-net :
                ipv4_address : 9.21.21.21
    mongodb :
        container_name : mongodb_ci_rabbitmq
        image : bitnami/mongodb:latest
        ports :
            - "24018:27017"
        networks :
            backend-net :
                ipv4_address : 9.21.21.22
        environment :
            - MONGODB_ROOT_PASSWORD=toor
            - MONGODB_USERNAME=root
            - MONGODB_PASSWORD=root
            - MONGODB_DATABASE=mbd_ci
    rabbitmq :
        build :
            context : ./docker/rabbitmq
            dockerfile : Dockerfile 
        container_name : ci_rabbitmq
        environment :
            RABBITMQ_DEFAULT_VHOST : /
            RABBITMQ_DEFAULT_USER : root
            RABBITMQ_DEFAULT_PASS : 7toor35*
            RABBITMQ_VM_MEMORY_HIGH_WATERMARK : 0.5
        ports :
            - "10672:15672"
            - "9672:5672"
        networks :
            backend-net :
                ipv4_address : 9.21.21.23
        volumes:
            - 'db-data:/var/lib/rabbitmq'

volumes:
    db-data:
        driver: local

networks :
    backend-net :
        driver : bridge
        ipam :
            driver : default
            config :
                - subnet : 9.21.21.0/26